#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
echo "$$" > /var/run/holbertonscript.pid

# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal
trap 'echo "I hate the kill command" && termfunc' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT

# Displays To infinity and beyond indefinitely
while true
do
	echo "To infinity and beyond"
	sleep 2

done
