#!/usr/bin/env bash
# This script displays "Best School 9 times"
# on the 9th line displays "Hi"
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    (( x ++ ))
done
