#!/usr/bin/env bash
# This script displays "Best School 9 time"
# on the 4th line displays "bad luck"
# on the 8th line displays "good luck"
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    fi
	if [ $x == 8 ]
	then
		echo "good luck"
	fi
    (( x ++ ))
done
